/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 8
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_COLON = 3,
  sym_process_name = 4,
  anon_sym_EQ = 5,
  sym__bare_option_value = 6,
  anon_sym_BANG = 7,
  sym_env_key = 8,
  sym__bare_env_value = 9,
  anon_sym_SQUOTE = 10,
  aux_sym_single_quoted_string_token1 = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_double_quoted_string_token1 = 13,
  sym_escape_sequence = 14,
  sym__newline = 15,
  sym__indent = 16,
  sym__dedent = 17,
  sym__command_text = 18,
  sym__multiline_command_text = 19,
  sym_line_continuation = 20,
  sym_option_key = 21,
  sym_bare_glob = 22,
  sym_source_file = 23,
  sym__definition = 24,
  sym_comment = 25,
  sym_process_definition = 26,
  sym_declaration = 27,
  sym__declaration_item = 28,
  sym_option = 29,
  sym_option_value = 30,
  sym_glob_pattern = 31,
  sym_exclusion_pattern = 32,
  sym_execution = 33,
  sym_env_var = 34,
  sym_env_value = 35,
  sym_command = 36,
  sym_multiline_block = 37,
  sym_block_line = 38,
  sym__quoted_string = 39,
  sym_single_quoted_string = 40,
  sym_double_quoted_string = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_declaration_repeat1 = 43,
  aux_sym_execution_repeat1 = 44,
  aux_sym_multiline_block_repeat1 = 45,
  aux_sym_double_quoted_string_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_COLON] = ":",
  [sym_process_name] = "process_name",
  [anon_sym_EQ] = "=",
  [sym__bare_option_value] = "_bare_option_value",
  [anon_sym_BANG] = "!",
  [sym_env_key] = "env_key",
  [sym__bare_env_value] = "_bare_env_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_quoted_string_token1] = "single_quoted_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_quoted_string_token1] = "double_quoted_string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__command_text] = "_command_text",
  [sym__multiline_command_text] = "_multiline_command_text",
  [sym_line_continuation] = "line_continuation",
  [sym_option_key] = "option_key",
  [sym_bare_glob] = "bare_glob",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_comment] = "comment",
  [sym_process_definition] = "process_definition",
  [sym_declaration] = "declaration",
  [sym__declaration_item] = "_declaration_item",
  [sym_option] = "option",
  [sym_option_value] = "option_value",
  [sym_glob_pattern] = "glob_pattern",
  [sym_exclusion_pattern] = "exclusion_pattern",
  [sym_execution] = "execution",
  [sym_env_var] = "env_var",
  [sym_env_value] = "env_value",
  [sym_command] = "command",
  [sym_multiline_block] = "multiline_block",
  [sym_block_line] = "block_line",
  [sym__quoted_string] = "_quoted_string",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_double_quoted_string] = "double_quoted_string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_declaration_repeat1] = "declaration_repeat1",
  [aux_sym_execution_repeat1] = "execution_repeat1",
  [aux_sym_multiline_block_repeat1] = "multiline_block_repeat1",
  [aux_sym_double_quoted_string_repeat1] = "double_quoted_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_process_name] = sym_process_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__bare_option_value] = sym__bare_option_value,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_env_key] = sym_env_key,
  [sym__bare_env_value] = sym__bare_env_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_quoted_string_token1] = aux_sym_single_quoted_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_quoted_string_token1] = aux_sym_double_quoted_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__command_text] = sym__command_text,
  [sym__multiline_command_text] = sym__multiline_command_text,
  [sym_line_continuation] = sym_line_continuation,
  [sym_option_key] = sym_option_key,
  [sym_bare_glob] = sym_bare_glob,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_comment] = sym_comment,
  [sym_process_definition] = sym_process_definition,
  [sym_declaration] = sym_declaration,
  [sym__declaration_item] = sym__declaration_item,
  [sym_option] = sym_option,
  [sym_option_value] = sym_option_value,
  [sym_glob_pattern] = sym_glob_pattern,
  [sym_exclusion_pattern] = sym_exclusion_pattern,
  [sym_execution] = sym_execution,
  [sym_env_var] = sym_env_var,
  [sym_env_value] = sym_env_value,
  [sym_command] = sym_command,
  [sym_multiline_block] = sym_multiline_block,
  [sym_block_line] = sym_block_line,
  [sym__quoted_string] = sym__quoted_string,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_declaration_repeat1] = aux_sym_declaration_repeat1,
  [aux_sym_execution_repeat1] = aux_sym_execution_repeat1,
  [aux_sym_multiline_block_repeat1] = aux_sym_multiline_block_repeat1,
  [aux_sym_double_quoted_string_repeat1] = aux_sym_double_quoted_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_process_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__bare_option_value] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_env_key] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_env_value] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__command_text] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_command_text] = {
    .visible = false,
    .named = true,
  },
  [sym_line_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_option_key] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_glob] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_process_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration_item] = {
    .visible = false,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_option_value] = {
    .visible = true,
    .named = true,
  },
  [sym_glob_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_exclusion_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_execution] = {
    .visible = true,
    .named = true,
  },
  [sym_env_var] = {
    .visible = true,
    .named = true,
  },
  [sym_env_value] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_line] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execution_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 27,
  [32] = 22,
  [33] = 33,
  [34] = 34,
  [35] = 12,
  [36] = 36,
  [37] = 18,
  [38] = 14,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 47,
  [53] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') SKIP(6);
      if (lookahead == '#') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_process_name);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_process_name);
      if (lookahead == '!') ADVANCE(12);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_process_name);
      if (lookahead == '!') ADVANCE(12);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__bare_option_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != ':') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_env_key);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__bare_env_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_single_quoted_string_token1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_single_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_double_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 6, .external_lex_state = 2},
  [6] = {.lex_state = 6, .external_lex_state = 2},
  [7] = {.lex_state = 1, .external_lex_state = 4},
  [8] = {.lex_state = 2, .external_lex_state = 5},
  [9] = {.lex_state = 3, .external_lex_state = 5},
  [10] = {.lex_state = 1, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 6, .external_lex_state = 6},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 6, .external_lex_state = 6},
  [20] = {.lex_state = 0, .external_lex_state = 7},
  [21] = {.lex_state = 1, .external_lex_state = 4},
  [22] = {.lex_state = 4, .external_lex_state = 5},
  [23] = {.lex_state = 6, .external_lex_state = 2},
  [24] = {.lex_state = 4, .external_lex_state = 5},
  [25] = {.lex_state = 6, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 8},
  [27] = {.lex_state = 4, .external_lex_state = 5},
  [28] = {.lex_state = 6, .external_lex_state = 2},
  [29] = {.lex_state = 6, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 8},
  [31] = {.lex_state = 4, .external_lex_state = 5},
  [32] = {.lex_state = 4, .external_lex_state = 5},
  [33] = {.lex_state = 1, .external_lex_state = 4},
  [34] = {.lex_state = 1, .external_lex_state = 4},
  [35] = {.lex_state = 1, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 9},
  [37] = {.lex_state = 1, .external_lex_state = 4},
  [38] = {.lex_state = 1, .external_lex_state = 4},
  [39] = {.lex_state = 0, .external_lex_state = 8},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 5},
  [47] = {.lex_state = 0, .external_lex_state = 5},
  [48] = {.lex_state = 0, .external_lex_state = 5},
  [49] = {.lex_state = 0, .external_lex_state = 5},
  [50] = {.lex_state = 22, .external_lex_state = 5},
  [51] = {.lex_state = 9, .external_lex_state = 5},
  [52] = {.lex_state = 0, .external_lex_state = 5},
  [53] = {.lex_state = 22, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_process_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_env_key] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__command_text] = ACTIONS(1),
    [sym__multiline_command_text] = ACTIONS(1),
    [sym_line_continuation] = ACTIONS(3),
    [sym_option_key] = ACTIONS(1),
    [sym_bare_glob] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__definition] = STATE(6),
    [sym_comment] = STATE(6),
    [sym_process_definition] = STATE(6),
    [sym_declaration] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_process_name] = ACTIONS(9),
    [sym__newline] = ACTIONS(11),
    [sym_line_continuation] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_option_key,
    ACTIONS(23), 1,
      sym_bare_glob,
    STATE(13), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
    STATE(3), 5,
      sym__declaration_item,
      sym_option,
      sym_glob_pattern,
      sym_exclusion_pattern,
      aux_sym_declaration_repeat1,
  [34] = 9,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_option_key,
    ACTIONS(23), 1,
      sym_bare_glob,
    ACTIONS(25), 1,
      anon_sym_COLON,
    STATE(13), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
    STATE(4), 5,
      sym__declaration_item,
      sym_option,
      sym_glob_pattern,
      sym_exclusion_pattern,
      aux_sym_declaration_repeat1,
  [68] = 9,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(27), 1,
      anon_sym_COLON,
    ACTIONS(29), 1,
      anon_sym_BANG,
    ACTIONS(32), 1,
      anon_sym_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(38), 1,
      sym_option_key,
    ACTIONS(41), 1,
      sym_bare_glob,
    STATE(13), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
    STATE(4), 5,
      sym__declaration_item,
      sym_option,
      sym_glob_pattern,
      sym_exclusion_pattern,
      aux_sym_declaration_repeat1,
  [102] = 7,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      sym_process_name,
    ACTIONS(52), 1,
      sym__newline,
    STATE(49), 1,
      sym_declaration,
    STATE(5), 4,
      sym__definition,
      sym_comment,
      sym_process_definition,
      aux_sym_source_file_repeat1,
  [127] = 7,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_process_name,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      sym__newline,
    STATE(49), 1,
      sym_declaration,
    STATE(5), 4,
      sym__definition,
      sym_comment,
      sym_process_definition,
      aux_sym_source_file_repeat1,
  [152] = 7,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(59), 1,
      sym_env_key,
    ACTIONS(61), 1,
      sym__newline,
    ACTIONS(63), 1,
      sym__command_text,
    STATE(41), 1,
      sym_execution,
    STATE(43), 1,
      sym_command,
    STATE(10), 2,
      sym_env_var,
      aux_sym_execution_repeat1,
  [175] = 6,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      sym__bare_option_value,
    STATE(17), 1,
      sym_option_value,
    STATE(16), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [196] = 6,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(67), 1,
      sym__bare_env_value,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_env_value,
    STATE(34), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [217] = 6,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(59), 1,
      sym_env_key,
    ACTIONS(63), 1,
      sym__command_text,
    ACTIONS(73), 1,
      sym__newline,
    STATE(42), 1,
      sym_command,
    STATE(21), 2,
      sym_env_var,
      aux_sym_execution_repeat1,
  [237] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(75), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [249] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(77), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [261] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(79), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [273] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(81), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [285] = 4,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(85), 1,
      sym__indent,
    STATE(25), 1,
      sym_multiline_block,
    ACTIONS(83), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [301] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(87), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [313] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(89), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [325] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(91), 6,
      sym_option_key,
      sym_bare_glob,
      anon_sym_COLON,
      anon_sym_BANG,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [337] = 4,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(85), 1,
      sym__indent,
    STATE(28), 1,
      sym_multiline_block,
    ACTIONS(93), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [353] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_bare_glob,
    STATE(11), 3,
      sym__quoted_string,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [371] = 4,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(97), 1,
      sym_env_key,
    ACTIONS(100), 2,
      sym__newline,
      sym__command_text,
    STATE(21), 2,
      sym_env_var,
      aux_sym_execution_repeat1,
  [386] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(102), 1,
      anon_sym_DQUOTE,
    ACTIONS(104), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(106), 1,
      sym_escape_sequence,
    STATE(24), 1,
      aux_sym_double_quoted_string_repeat1,
  [402] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(108), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [412] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(115), 1,
      sym_escape_sequence,
    STATE(24), 1,
      aux_sym_double_quoted_string_repeat1,
  [428] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(93), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [438] = 4,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(118), 1,
      sym__dedent,
    ACTIONS(120), 1,
      sym__multiline_command_text,
    STATE(30), 2,
      sym_block_line,
      aux_sym_multiline_block_repeat1,
  [452] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    ACTIONS(124), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(126), 1,
      sym_escape_sequence,
    STATE(22), 1,
      aux_sym_double_quoted_string_repeat1,
  [468] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(128), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [478] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(130), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_process_name,
  [488] = 4,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(132), 1,
      sym__dedent,
    ACTIONS(134), 1,
      sym__multiline_command_text,
    STATE(30), 2,
      sym_block_line,
      aux_sym_multiline_block_repeat1,
  [502] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(137), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(141), 1,
      sym_escape_sequence,
    STATE(32), 1,
      aux_sym_double_quoted_string_repeat1,
  [518] = 5,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(104), 1,
      aux_sym_double_quoted_string_token1,
    ACTIONS(106), 1,
      sym_escape_sequence,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_double_quoted_string_repeat1,
  [534] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(145), 3,
      sym__newline,
      sym__command_text,
      sym_env_key,
  [543] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(147), 3,
      sym__newline,
      sym__command_text,
      sym_env_key,
  [552] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(77), 3,
      sym__newline,
      sym__command_text,
      sym_env_key,
  [561] = 3,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(120), 1,
      sym__multiline_command_text,
    STATE(26), 2,
      sym_block_line,
      aux_sym_multiline_block_repeat1,
  [572] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(91), 3,
      sym__newline,
      sym__command_text,
      sym_env_key,
  [581] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(81), 3,
      sym__newline,
      sym__command_text,
      sym_env_key,
  [590] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(149), 2,
      sym__dedent,
      sym__multiline_command_text,
  [598] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(151), 1,
      sym__newline,
  [605] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(153), 1,
      sym__newline,
  [612] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(155), 1,
      sym__newline,
  [619] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(73), 1,
      sym__newline,
  [626] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(157), 1,
      sym__newline,
  [633] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
  [640] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(161), 1,
      anon_sym_EQ,
  [647] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(163), 1,
      anon_sym_SQUOTE,
  [654] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(165), 1,
      anon_sym_EQ,
  [661] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(167), 1,
      anon_sym_COLON,
  [668] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(169), 1,
      aux_sym_single_quoted_string_token1,
  [675] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(171), 1,
      aux_sym_comment_token1,
  [682] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_SQUOTE,
  [689] = 2,
    ACTIONS(3), 1,
      sym_line_continuation,
    ACTIONS(175), 1,
      aux_sym_single_quoted_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 127,
  [SMALL_STATE(7)] = 152,
  [SMALL_STATE(8)] = 175,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 217,
  [SMALL_STATE(11)] = 237,
  [SMALL_STATE(12)] = 249,
  [SMALL_STATE(13)] = 261,
  [SMALL_STATE(14)] = 273,
  [SMALL_STATE(15)] = 285,
  [SMALL_STATE(16)] = 301,
  [SMALL_STATE(17)] = 313,
  [SMALL_STATE(18)] = 325,
  [SMALL_STATE(19)] = 337,
  [SMALL_STATE(20)] = 353,
  [SMALL_STATE(21)] = 371,
  [SMALL_STATE(22)] = 386,
  [SMALL_STATE(23)] = 402,
  [SMALL_STATE(24)] = 412,
  [SMALL_STATE(25)] = 428,
  [SMALL_STATE(26)] = 438,
  [SMALL_STATE(27)] = 452,
  [SMALL_STATE(28)] = 468,
  [SMALL_STATE(29)] = 478,
  [SMALL_STATE(30)] = 488,
  [SMALL_STATE(31)] = 502,
  [SMALL_STATE(32)] = 518,
  [SMALL_STATE(33)] = 534,
  [SMALL_STATE(34)] = 543,
  [SMALL_STATE(35)] = 552,
  [SMALL_STATE(36)] = 561,
  [SMALL_STATE(37)] = 572,
  [SMALL_STATE(38)] = 581,
  [SMALL_STATE(39)] = 590,
  [SMALL_STATE(40)] = 598,
  [SMALL_STATE(41)] = 605,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 619,
  [SMALL_STATE(44)] = 626,
  [SMALL_STATE(45)] = 633,
  [SMALL_STATE(46)] = 640,
  [SMALL_STATE(47)] = 647,
  [SMALL_STATE(48)] = 654,
  [SMALL_STATE(49)] = 661,
  [SMALL_STATE(50)] = 668,
  [SMALL_STATE(51)] = 675,
  [SMALL_STATE(52)] = 682,
  [SMALL_STATE(53)] = 689,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execution, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exclusion_pattern, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_glob_pattern, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_string, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_value, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_string, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_execution_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_execution_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition, 5, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_block, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_block_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_var, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_value, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_line, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execution, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token__command_text = 3,
  ts_external_token__multiline_command_text = 4,
  ts_external_token_line_continuation = 5,
  ts_external_token_option_key = 6,
  ts_external_token_bare_glob = 7,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__command_text] = sym__command_text,
  [ts_external_token__multiline_command_text] = sym__multiline_command_text,
  [ts_external_token_line_continuation] = sym_line_continuation,
  [ts_external_token_option_key] = sym_option_key,
  [ts_external_token_bare_glob] = sym_bare_glob,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__command_text] = true,
    [ts_external_token__multiline_command_text] = true,
    [ts_external_token_line_continuation] = true,
    [ts_external_token_option_key] = true,
    [ts_external_token_bare_glob] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_line_continuation] = true,
  },
  [3] = {
    [ts_external_token_line_continuation] = true,
    [ts_external_token_option_key] = true,
    [ts_external_token_bare_glob] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__command_text] = true,
    [ts_external_token_line_continuation] = true,
  },
  [5] = {
    [ts_external_token_line_continuation] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token_line_continuation] = true,
  },
  [7] = {
    [ts_external_token_line_continuation] = true,
    [ts_external_token_bare_glob] = true,
  },
  [8] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__multiline_command_text] = true,
    [ts_external_token_line_continuation] = true,
  },
  [9] = {
    [ts_external_token__multiline_command_text] = true,
    [ts_external_token_line_continuation] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_procfile_external_scanner_create(void);
void tree_sitter_procfile_external_scanner_destroy(void *);
bool tree_sitter_procfile_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_procfile_external_scanner_serialize(void *, char *);
void tree_sitter_procfile_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_procfile(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_procfile_external_scanner_create,
      tree_sitter_procfile_external_scanner_destroy,
      tree_sitter_procfile_external_scanner_scan,
      tree_sitter_procfile_external_scanner_serialize,
      tree_sitter_procfile_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "procfile",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
